import Head from 'next/head'
import Features from '../components/home/Features'
import ServiceContainer from '../components/home/ServiceContainer'
import Slider from '../components/home/Slider'
import TopBar from '../components/home/TopBar'
import SpecialProducts from '../components/home/SpecialProducts'
import HomeFooter from '../components/home/HomeFooter'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <TopBar />
        <hr className='my-2' />
        <Slider />
        <hr className='my-2' />
        <SpecialProducts/>
        <hr className='my-2' />
        <Features />
<HomeFooter/>
      </main>
    </div>
  )
}
